;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        consult-yank-pop
        cycle-spacing
        dabbrev-expand
        dired-flag-file-deletion
        electric-newline-and-maybe-indent
        forward-symbol
        ignore
        indent-for-tab-command
        kill-region
        mark-word
        meow-append
        meow-back-symbol
        meow-back-word
        meow-beginning-of-thing
        meow-cancel-selection
        meow-change
        meow-delete
        meow-end-of-thing
        meow-expand-1
        meow-expand-2
        meow-find
        meow-inner-of-thing
        meow-insert
        meow-insert-exit
        meow-keypad
        meow-kill
        meow-left
        meow-left-expand
        meow-line
        meow-mark-symbol
        meow-next
        meow-next-symbol
        meow-next-word
        meow-open-below
        meow-pop-selection
        meow-prev
        meow-replace
        meow-right
        meow-right-expand
        meow-save
        meow-till
        meow-undo
        meow-yank
        repeat
        ))

(setq mc/cmds-to-run-once
      '(
        mc/toggle-cursor-on-click
        meow-grab
        multiple-cursors-mode
        ))
