;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        consult-yank-pop
        dabbrev-expand
        electric-newline-and-maybe-indent
        ignore
        meow-append
        meow-back-symbol
        meow-back-word
        meow-cancel-selection
        meow-change
        meow-delete
        meow-end-of-thing
        meow-expand-1
        meow-expand-2
        meow-find
        meow-inner-of-thing
        meow-insert
        meow-insert-exit
        meow-keypad
        meow-kill
        meow-left
        meow-left-expand
        meow-next
        meow-next-symbol
        meow-next-word
        meow-pop-selection
        meow-prev
        meow-right
        meow-right-expand
        meow-save
        meow-till
        meow-undo
        meow-yank
        repeat
        ))

(setq mc/cmds-to-run-once
      '(
        meow-grab
        multiple-cursors-mode
        ))
